### ISSUE TITLE
[Website] Missing contact information for partners/sponsors

### ISSUE THREAD

**Issue by kdubois** [BeJUG/bejug.github.io#10]
**Describe the bug**
The partnership guidelines doc should have an actionable link to where potentially interested parties can contact the group for more information.   

**To Reproduce**
Go to 
[https://belgian-jug.github.io/docs/partnership-guidelines . ](https://bejug.github.io/partnership-guidelines) 

**Expected behavior**
A link to a contact page that lists some ways they can get in touch

**Comment by TomCools** [comment]
Excellent remark Kevin! I'll look into that soon!
