### ISSUE TITLE
[Meetup] May 2023

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#11]
### Preparation

- [ ] Find speaker(s)
- [x] Find location
- [ ] Determine date
- [ ] Announce event on Meetup.com
- [ ] Promote on social media

### After the event

- [ ] Send mail to attendees to wrap up
- [ ] Shoutouts on social media
- [ ] Share content (slides / video / images) if/when available
- [ ] Promote next event (If available)

**Comment by TomCools** [comment]
Tom B?

**Comment by Tom-Br** [comment]
Yes DPG Media would be happy to host de BeJUG in may.

**Comment by Tom-Br** [comment]
Suggestion for the date: 21/05/2023

**Comment by TomCools** [comment]
Idea: Speaker mentoring

**Comment by TomCools** [comment]
Meetup will not progress in favor of Speaker training end of April, only Voxxed in May.
