### ISSUE TITLE
[Meetup] June 2023

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#12]
### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by kdubois** [comment]
@TomCools Red Hat could sponsor this one and find a location.  Do we want to combine with the BBQ idea?

**Comment by TomCools** [comment]
Going to talk to Emily Jiang and Grace Jansen at JavaLand for details. 
Might be a good fit for the https://github.com/BeJUG/bejug.github.io/issues/17 collab with WomenCodeBe collaboration.

**Comment by TomCools** [comment]
Thursday (22th) or Friday (23th) of June. Thursday has our preference.

**Comment by TomCools** [comment]
22th has been confirmed with Grace! WomenCode idea will be postponed till later this year.

**Comment by TomCools** [comment]
Once I get the subjects from Emily and Grace, we are good to go. Location is arranged.

**Comment by TomCools** [comment]
Waiting for slides to wrap this one up with a mail.
