### ISSUE TITLE
[Event] March 2023: Call for speakers

### ISSUE THREAD

**Issue by FDelporte** [BeJUG/bejug.github.io#14]
You want to speak to the BeJUG event in Kortrijk on Monday, March 20th? Let us know!
We reserve the first hour for a few short talks! Please, add your proposal here in this ticket...

Be warned! If you don't do it, the organizers will talk too long about [BeJUG](https://bejug.github.io/), [Foojay.io](https://foojay.io/), [#JavaOnRaspberryPi](https://twitter.com/hashtag/JavaOnRaspberryPi), etc. ;-)

* 18:00: Doors + food
* 19:00: Short sessions
* 20:00: What the CRaC - Superfast JVM startup

**Comment by FDelporte** [comment]
First proposal: 
* @wimdeblauwe
* 15' about https://github.com/wimdeblauwe/error-handling-spring-boot-starter

**Comment by rdehuyss** [comment]
Second proposal:

- @rdehuyss
- 15' about https://github.com/jobrunr/jobrunr

**Comment by FDelporte** [comment]
thanks @rdehuyss !

**Comment by FDelporte** [comment]
schedule is being finalized, will publish on meetup page as soon as I have all info
