### ISSUE TITLE
[Event] FOSDEM: how can we participate

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#2]
A task to discuss how we can participate in FOSDEM
Thoughts:

- Promo?
- Speaker Training?
- Booth?
- Surrounding Java activity?

**Comment by geertjanw** [comment]
Definitely at least everyone should submit content to the friends of OpenJDK devroom:

https://foojay.io/today/friends-of-openjdk-at-fosdem-2023/

**Comment by TomCools** [comment]
Sent Tweet to promote.
