### ISSUE TITLE
[Meetup] July - BRAAAAZZZZIIILLLL!

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#21]
### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

## Context and additional details

Bruno (JavaMan) Souza is traveling over to our JUG on Friday 7th of July.
I also invited another Brazilian, Elias Nogueira (lives in NL) to have a Brazilian themed event.

**Comment by lmagnette** [comment]
@TomCools it should be ok for the food and the outside projection. I'm just waiting for confirmation that I should get tomorrow

**Comment by lmagnette** [comment]
@TomCools I've just got confirmation that everything is ok (outside projection, food and drinks).

**Comment by TomCools** [comment]
Cool. I'll align with the speakers! What is the capacity? 😊 how many folks can we invite?

**Comment by lmagnette** [comment]
The estimated capacity would be around 50 people, with the possibility of accommodating a few more if needed.

**Comment by TomCools** [comment]
@lmagnette, excellent! I doubt we'll get that many attendees, but let's try this! 
I'll reach out to the speakers and make sure they can get there and they need to give me the talk names ;). 
I am aiming to announce this meetup on friday, 3 weeks ahead of time should be enough.

Thanks for the effort! :)

**Comment by TomCools** [comment]
Announcement going out on monday due to some family stuff. @lmagnette.

**Comment by TomCools** [comment]
@lmagnette, it's announced, also on LinkedIn this time (we'll do that for every event now). 
Since this meetup includes food, I'll send a reminder to change the RSVP at the beginning of July. We've been getting a lot of No-shows and last minutes RSVP changes, trying to avoid that in the future. 

You can follow the amount of signups on the meetup page: https://www.meetup.com/belgian-java-user-group/events/294251222/

**Comment by lmagnette** [comment]
@TomCools Just wanted to give you a quick update on the upcoming BeJUG meetup. We've arranged a small aperitif with chips and drinks to kick things off at 18:00.  For dinner, we've got pizzas coming in around 20:00.

Before finalizing everything, I wanted to check in with you. Does this plan sound good to you? Let me know your thoughts.

**Comment by TomCools** [comment]
Sounds good to me @lmagnette
