### ISSUE TITLE
[Meetup] September

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#23]
### Preparation

- [x] Find speaker(s) @octonato and Edwin
- [x] Find location  Interleuvenlaan 74 in Heverlee (If the subscription would drop lower - say only 30 - we could go across the street to a more cosy setting, that would be Interleuvenlaan 27B)
- [x] Determine date  07/09/2023
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [ ] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by TomCools** [comment]
Istvan will pick this one up :)

**Comment by ioosterl** [comment]
Indeed, I can help out with a location.
We can provide food and drinks for 50-70 people

**Comment by TomCools** [comment]
@ioosterl: I am currently trying to recruit speakers for this one 👍 I'll drop a message here if I found some. 
Could you comment the exact location where this could take place and any limitations you see?

**Comment by ioosterl** [comment]
@TomCools 
Exact address is Interleuvenlaan 74, 3001 Leuven
Maximum capacity is about 70 people.
If the expected attendance is lower, we can reduce the size of the room to make it more cosy

Only other potential issue I see is if the date would be September 19th

**Comment by TomCools** [comment]
Perfect, let me look around for some speakers! :)

**Comment by TomCools** [comment]
@ioosterl, did you talk to Edwin about this? 
Also, @octonato could be a speaker already. If Edwin can't come, then I would suggest Quicky sessions? :)

**Comment by octonato** [comment]
Yes, I can. 

But I'm confused about your question. Are you asking me to give a long talk if Edwin can't come? If that's the case, yes, I can do it in September.

Or are you asking me to give a quicky session instead?

**Comment by octonato** [comment]
Hmm, I think I understand it now. You are looking for two speakers, me and Edwin. And if he can't come we fill his slot with Quickies, correct?

I have another suggestion, I have two talks that are complementary. The one I submitted here and another one about Saga Pattern (Choreography and Orchestration). If you guys really want to hear me talk for 2 hours, I can do both on the same day. 😄

**Comment by TomCools** [comment]
Yes! The 2nd 😅. 2h might be a bit too much Renato. 😅

**Comment by ioosterl** [comment]
Great news.
I had a chat with both Maarten and Edwin last friday, but I haven't finalized anything.
I'm looking for the first full week of September (4-8). Would that fit for you @octonato ?

**Comment by ioosterl** [comment]
Well, the way things were shaping up, I am no longer available second week
so that would be kind of hard to host the even then ;)
I've checked in with Edwin, he would prefer september 7th.
If you can make that work as well, I think we have our date.

Op wo 12 jul 2023 om 22:00 schreef Renato Cavalcanti <
***@***.***>:

**Comment by octonato** [comment]
That's fine. I can make it on the 7th. Let's stick with it.

**Comment by ioosterl** [comment]
It looks like we have our date then.
I've reserverd the location.
I propose @octonato  that your talk is first, Edwin has a lot of travel to do so this way we can have some buffer in case traffic intervienes

**Comment by ioosterl** [comment]
@TomCools 
Looks like we check some boxes on the task list (i don't seem to be able t do that):
Date:  07/09/2023
Location: Interleuvenlaan 74 in Heverlee (If the subscription would drop lower - say only 30 - we could go across the street to a more cosy setting, that would be Interleuvenlaan 27B)
Speakers: @octonato and Edwin

Do you require anything extra to do the announcement and promotion on Social Media?

PS: I trying to look for an alternative to pizza as food, but no promises yet

**Comment by TomCools** [comment]
@ioosterl. Excellent work! :) All I would need is the name/logo/socials of the hosting company and for the meetup.com page i'd need an abstract and bio from each speaker ;)  

@octonato, you already posted https://github.com/BeJUG/bejug.github.io/issues/29, is this the abstract I can use? And do you have a bio you would like me to use?

For Edwin, I'll check with him directly ;), i got the link to his Devoxx submission ^^

**Comment by octonato** [comment]
@TomCools, sure. Here is the Bio I usually use in talks.

Renato is a software developer at Lightbend, working in the Kalix and Akka Teams. Scala aficionado since 2009, has been hacking in Scala and related technologies for fun and profit. He is interested in Event Sourcing/CQRS, DDD and Microservices  Architectures. He's the founder of BeScala (Belgian Scala User Group).

**Comment by ioosterl** [comment]
@TomCools Hereby the logo and the socials for AE
![logo_AE](https://github.com/BeJUG/bejug.github.io/assets/14086799/f457c5b3-801c-4571-a13e-c202bacf69f4)

LinkedIn :https://www.linkedin.com/company/ae-consultants/
Twitter: @AE_NV

**Comment by TomCools** [comment]
@ioosterl sorry for the delay. Child being born and such ;). 

Could you check the draft page: https://www.meetup.com/belgian-java-user-group/events/295051128/? 
If you give the OK, I'll post it sometime during the week.

and the card:
![September Event (1)](https://github.com/BeJUG/bejug.github.io/assets/11362563/c8fc180b-09c3-460d-9ed5-4a6bad469ae0)

**Comment by ioosterl** [comment]
@TomCools No worries, we stil got a bit of time, and be all means congratz on becomming a dad!

As for the draft, I would not put pizzas in between the 2 sessions as that could be a bit annoying logisticly and it Will not be pizza but plenty of other food that can be considered dinner 😉

I will try to arrange with our facilities team that food will be there before the sessions, especially. So timing would be something like 18h food and drinks, 19h first session, 20h next session, with some mingling afterwards.

I will finalize with facilities a week before the event. I guess that we can issue an update if needed?

**Comment by TomCools** [comment]
It's adjusted. Issuing an update is always possible ;) but we do try to keep the updates as low as possible because it creates confusion :).

**Comment by ioosterl** [comment]
As soon as it is posted i will inform our marketing team as well

**Comment by ioosterl** [comment]
@TomCools can you share the social media posts so our marketing team can pick it up?

**Comment by SimonVerhoeven** [comment]
I saw posts on:

https://www.linkedin.com/feed/update/urn:li:activity:7098275534651969537?utm_source=share&utm_medium=member_desktop
https://twitter.com/BeJUG/status/1692157996372005175

I also shared it on bsky:
https://bsky.app/profile/simonverhoeven.bsky.social/post/3k5and3uib22u

**Comment by TomCools** [comment]
Was changing diapers and now @SimonVerhoeven beat me to it 😆

**Comment by ioosterl** [comment]
Thanks @SimonVerhoeven  and @TomCools

**Comment by octonato** [comment]
For the record, the abstract can be found here https://github.com/BeJUG/bejug.github.io/issues/29

**Comment by TomCools** [comment]
@octonato donno how we missed that. Sorry about that.
I have updated the page.

**Comment by ioosterl** [comment]
@octonato I missed it completely, even though @TomCools asked me to review it.
Thanks for fixing it Tom.

**Comment by ioosterl** [comment]
@TomCools , tomorrow I have final alignment meeting with our facilities team.
With the current number of participants and the current weather forecast, I might just steal the idea of the last meetup and host it in our "outdoor meeting room" on Interleuvenlaan 27b, which is diagonally across the street. We can put up signing if we change to make sure there is not too much confusion. Hope this is a small enough change that won't cause troubel

**Comment by TomCools** [comment]
As long as we guide people correctly and we have an alternative in case the weather goes to hell... i see no issue 😊

**Comment by TomCools** [comment]
Done, should still be on time.
