### ISSUE TITLE
[Meetup] October (Devoxx?)

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#24]
We can align with Devoxx on this, maybe some extra little thing around the day? Social events? 
Or at the end of the month, a recap? 

### Preparation

- [ ] Find speaker(s)
- [ ] Find location
- [ ] Determine date
- [ ] Announce event on Meetup.com
- [ ] Promote on social media

### After the event

- [ ] Send mail to attendees to wrap up
- [ ] Shoutouts on social media
- [ ] Share content (slides / video / images) if/when available
- [ ] Promote next event (If available)

**Comment by TomCools** [comment]
@Tom Bruyninx will check with DPG
@TomCools will check with WomenCode

**Comment by Tom-Br** [comment]
@TomCools happy to check. #WrongTom

**Comment by TomCools** [comment]
WomenCode is out of the picture for now :(. We'll do this event probably without them.

**Comment by TomCools** [comment]
Monday of 2nd - DPG

Speakers: To be determined after Devoxx Announcement.

**Comment by TomCools** [comment]
@Tom-Br , I reached out to some speakers. Hopefully will be able to lock them in ;)

**Comment by TomCools** [comment]
Seems like this has hit a big bump in the road. Will postpone to later event.
