### ISSUE TITLE
Devoxx Ideas

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#27]
- Walking Tour: Red star line?
- Brussel Tram Experience? 
- Zoo? 
- MAS Antwerp
- Nice places to eat (Twitter (X?!?) Thread?)
- Ghost Walk tour?
- Plantin Museum
- Flandria Boat / Water Bus?
- Brewery De Koninck
- Boardgames Playground
- "Geeky tour"

**Comment by FDelporte** [comment]
I can create an "Interesting places for Devoxx" on Foojay

**Comment by SimonVerhoeven** [comment]
if you want to combine eating with an activity Wima bowling or akin might also be an option?

**Comment by FDelporte** [comment]
Page is published on BeJUG website
https://bejug.github.io/visit-belgium-tips.html
