### ISSUE TITLE
[Talk] Event Sourced Applications without Grey Hair

### ISSUE THREAD

**Issue by octonato** [BeJUG/bejug.github.io#29]
Folks, I would like to suggest the following talk: 

## Event Sourced Applications without Grey Hair

Event sourcing has gained significant attention in the world of software development as a powerful architectural pattern for building robust and scalable applications. However, embracing event sourcing comes with its own set of challenges and pitfalls that can lead to hair-raising moments for developers.

In this talk, we delve into the fascinating realm of event sourcing and explore the main patterns and anti-patterns that can make or break your event-sourced application. We'll embark on a journey through the landscape of event-driven architectures, uncovering the secrets to designing and implementing event sourcing in a way that will keep your hair intact.

**Comment by octonato** [comment]
For the record, I can give this talk at any moment. 
Except on the first week of July and the whole month of August.

**Comment by TomCools** [comment]
I had commented it offline, but for the record, would love to have this talk! :-) Let's see where we can fit you in. September might be an option

**Comment by TomCools** [comment]
Closing this task, since it is solved by the one above ;)
