### ISSUE TITLE
[Meetup] December - Made In Belgium

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#31]
Meetup concept Idea: Belgian developers making Belgian Products.

### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by TomCools** [comment]
@ge0ffrey and @ronald can give talks about their products.
Already in talks with a host to host this one in Ghent, Ghelamco-arena.

**Comment by ronald** [comment]
@TomCools did you mention the wrong Ronald?

Greets from Germany

**Comment by TomCools** [comment]
It seems so! Sorry to bother you! 😅 but feel free to reach out if you want to talk at our JUG at some point. 🤣

**Comment by octonato** [comment]
> Ghelamco-arena

Now you are talking. That will be a mega-meetup!

**Comment by FDelporte** [comment]
Yes @octonato, with a capacity of 20,000 people we can have 6 Devoxx'es at one time :-) :-) :-)

**Comment by TomCools** [comment]
Well.. Techorama NL had 2 stages on the bleechers at Amsterdam Arena 😅 

Let's see if we can get like 50 people together or something.

**Comment by TomCools** [comment]
@ge0ffrey and @rdehuyss do you have any preference for availability for December period? I'm guessing pretty early in the month to avoid the holidays? I need to provide a date to the organisation so they can lock in the venue before september :).

**Comment by rdehuyss** [comment]
Hi @TomCools (aka papa)! Voor mij gaat enkel nog dinsdag 5 december. Ik heb toegezegd om vanaf 7 december in de US op JUG tour te gaan 🤓.

**Comment by TomCools** [comment]
5 December is set. JUVO is gonna try to get the Ghelamco Arena in Ghent, which will be a new province we land in. 

Speakers will be @rdehuyss and @ge0ffrey

**Comment by ge0ffrey** [comment]
I look forward to it 🙂

Op zo 27 aug. 2023 21:36 schreef Tom Cools ***@***.***>:

**Comment by TomCools** [comment]
@FDelporte will you take care of the "after event" tasks?

**Comment by FDelporte** [comment]
Thanks for the reminder @TomCools, were actually already done, just needed closing here...
