### ISSUE TITLE
[Talk] Apache Pulsar

### ISSUE THREAD

**Issue by jonasgeiregat** [BeJUG/bejug.github.io#36]
## Apache Pulsar

Yesterday I had to opportunity to present at the Ch'Ti JUG in Lille. Afterwards I had a nice chat with one of the founders and turns out he is a developer advocate for StreamNative a company which is heavy on Apache Pulsar. Being an developer advocate he was obviously very keen on giving a talk on Apache Pulsar at our BeJUG.

**Comment by jonasgeiregat** [comment]
Received Julien Jakubowski github handle @jak78 so he can join the conversation.

**Comment by jak78** [comment]
Hello everyone! Thanks @jonasgeiregat for inviting me to this conversation!
Feel free to check the following link to get more details on my talk: https://sessionize.com/s/julien-jakubowski-streamnative/apache-pulsar-finally-an-alternative-to-kafka/73290
You can watch it in action at Berlin Buzzwords: https://www.youtube.com/watch?v=QngU8ComJfo&t=4s
I'd love to meet the Belgian JUG community and discuss messaging & data streaming :-)

**Comment by jak78** [comment]
If you give me enough time on stage, I can add demos

**Comment by TomCools** [comment]
Hi everyone! Let's make this happen 😊 just not today, recovering from Devoxx. Will get back to you!

@jak78 do you have any specific location or timeframe you'd like to speak? If you are closeby traveling to another conference, we can try to work that in. 

Looking forward to hear more about this!

**Comment by jak78** [comment]
Great! 
I hope you enjoyed Devoxx. I was not able to attend this time, unfortunately. 

> do you have any specific location or timeframe you'd like to speak? 

I live in Lille: we're neighbors ☺️ so I don't have any specific constraints when it comes to traveling to Belgium, and I would love to speak in any Belgian city with a large and passionate IT community.

**Comment by jak78** [comment]
I recommend you propose 3-4 date options, and we can pick the one that works for everyone.

**Comment by jak78** [comment]
Hello! It’s been a month. Time flies ☺️. Any update on this? Thanks

**Comment by TomCools** [comment]
@jak78 how do you feel about 2nd half of Februari somewhere close to Lille? We could do either Brugge/Ghent area, maybe even Kortijk again? @FDelporte looping you in here. 😉

**Comment by jak78** [comment]
@TomCools @FDelporte Great for 2nd half of February! Distance from Lille is not an issue: I can travel to anywhere in Belgium.

**Comment by jak78** [comment]
@TomCools @FDelporte hey! Any update on this?

**Comment by FDelporte** [comment]
Hi @jak78, I'm looking for a location end of February in Kortrijk/Waregem. Hope to give more details soon...

**Comment by jak78** [comment]
Hi @FDelporte Great! Thanks

**Comment by jak78** [comment]
@FDelporte Feb 19 and 26 both work for me. Thanks!

**Comment by FDelporte** [comment]
Closing this issue, Julien is available on 19 and 26 of February, and both dates also work for SweetMustard.

**Comment by FDelporte** [comment]
@jak78 can you please send me (frank at webtechie dot be) the following for the Meetup page

•	Profile picture
•	Title of the talk
•	Description of the talk
•	Your bio

**Comment by jak78** [comment]
@FDelporte done :-)
