### ISSUE TITLE
[Meetup] Februari 2024

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#38]
### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by FDelporte** [comment]
Organise this one in West-Flanders?

**Comment by TomCools** [comment]
Fine by me, TVH?

**Comment by jonasgeiregat** [comment]
TVH responded positively but not final confirmation received. 🤞

**Comment by jonasgeiregat** [comment]
At TVH an internal request has been made for our event but as its a big company things will move slow.
They already stated that it will not be possible for February.

**Comment by FDelporte** [comment]
SweetMustard can host us at Nijverheidskaai 3 in Kortrijk at 19 or 26 February with Julien Jakubowski  as a speaker. Now looking for a second speaker that's available one of these dates...

**Comment by FDelporte** [comment]
Scheduled!
Monday, February 26th 
Speakers: Julien Jakubowski and Loïc Mathieu

**Comment by FDelporte** [comment]
@N1cky94 see the event page:
https://www.meetup.com/belgian-java-user-group/events/298755642/

Speakers: Loïc Mathieu and Julien Jakubowski

**Comment by N1cky94** [comment]
I noticed it and subscribed. :)thnx. Is there anything more I can do to help?

**Comment by N1cky94** [comment]
# Question

@FDelporte en @TomCools 
Ik heb mogelijks twee vouchers om 6 maanden IntelliJ Ultimate uit te proberen voor volgende week.
Is het ok om op het einde misschien terug een kleine quiz (2 vragen, 1 over elk topic te doen).
Degene de vraag het best beantwoord, juist beantwoord, krijgt een voucher?

Ik begrijp het ook helemaal als jullie dit liever niet hebben.
Groeten

**Comment by FDelporte** [comment]
OK voor mij, als jij @N1cky94 voor de vragen zorgt ;-)

**Comment by N1cky94** [comment]
> OK voor mij, als jij [@N1cky94](https://github.com/N1cky94) voor de vragen zorgt ;-)

Hahahaha, ik spreek wel even met de sprekers dan.
I'm still learning. ;)
