### ISSUE TITLE
[Meetup] April

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#40]
### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by lmagnette** [comment]
One of my old school would be interested to host one of this event: https://www.vinci.be/en

**Comment by lmagnette** [comment]
Everything looks ok for them to host the event the 23/04.

**Comment by TomCools** [comment]
Which campus of the school would the event be?

**Comment by lmagnette** [comment]
I would normally be at the Woluwe campus.

**Comment by TomCools** [comment]
Sami from Vaadin? (to be confirmed)
Olivier will send details of a Gatling speaker to Loic for a potential 2nd :)

**Comment by lmagnette** [comment]
Sami have just confirmed that he will be there 🥳. 
I've sent a message to @ohubaut to get the details from the Gatling speaker but didn't got any anwsers.

**Comment by lmagnette** [comment]
I've got the details for the Gatling speaker, but it will not be possible for april for them.

**Comment by TomCools** [comment]
So either a single speaker... or I can give a talk.

**Comment by lmagnette** [comment]
@TomCools I'm totally ok with you giving a talk.  So I would go with 2 speakers  Sami and you :-)

**Comment by TomCools** [comment]
@lmagnette i need an abstract, title and bio from Sami 😊 so i can make the announcement. I know my own stuff

**Comment by lmagnette** [comment]
Title: You Can Build Web UI Using Java Only

Abstract:
In the fast-evolving landscape of web development, Java remains a cornerstone for robust backend systems. However, its potential in frontend development is often overshadowed by JavaScript-dominated frameworks. This session aims to shift this perspective by introducing Vaadin, a Java-based framework designed for building modern web user interfaces.

The session will commence with a brief introduction to Java's role in current web development scenarios, highlighting its stability, scalability, and security features. We will then pivot to an in-depth exploration of Vaadin, showcasing how this innovative framework leverages Java's strengths to create efficient, responsive, and visually appealing web UIs.

**Comment by lmagnette** [comment]
Oh and btw here's the logo of the host ![VINCI_FC_logo_blue.jpg](https://github.com/BeJUG/bejug.github.io/assets/6390187/2ab4e929-105b-4077-a936-802e0b55f2b7)

**Comment by TomCools** [comment]
@lmagnette Is any kind of drink included? Or is just purely the event?

**Comment by lmagnette** [comment]
@TomCools drinks and some snacks are included

**Comment by TomCools** [comment]
@lmagnette Also, which exact location on campus? :) because looking on their website, there are multiple adresses.

Place de l'Alma, 3
Promenade de l'Alma, 59
Clos Chapelle-aux-Champs, 41
Clos Chapelle-aux-Champs, 43
Avenue Emmanuel Mounier, 84

https://www.vinci.be/en/campuses/campus-woluwe

**Comment by lmagnette** [comment]
It will be at "clos chapelle aux champs 43 - 1200 Bruxelles" in the auditorium CHP43 B11.

**Comment by TomCools** [comment]
@lmagnette save it as a draft, you should be able to reach it now. Feel free to post and announce on Meetup when you think it's good.: https://www.meetup.com/belgian-java-user-group/events/drafts/

You can post a nice message on LinkedIn yourself (usually just the BeJUG group, then we repost) and I gave you rights to post with the BeJUG account on X/Twitter ;). If you need any further help, let me know!

Card:

![April event](https://github.com/BeJUG/bejug.github.io/assets/11362563/9485fc4d-7b0e-4999-a881-915016cb0e23)

**Comment by lmagnette** [comment]
The event is published and I've posted on X and LinkedIn.
