### ISSUE TITLE
[Meetup] May 2024

### ISSUE THREAD

**Issue by FDelporte** [BeJUG/bejug.github.io#41]
### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [ ] Send mail to attendees to wrap up
- [ ] Shoutouts on social media
- [ ] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by lmagnette** [comment]
Oniryx confirmed we can have the May session in Gembloux (hopefully outside like last year).
Possible dates: 15/05,16/05, 23/05, 30/05, 31/05.
We could maybe take advantage of the voxxed days brussels being near to get some speakers.

**Comment by TomCools** [comment]
Maybe 29th for speakers for Spring IO?
We'll exclude the 23th because too close to Voxxed Days Brussels

**Comment by lmagnette** [comment]
I've checked and they would be ok to host it the 29th.
For the speaker Guillaume Laforge could be available this time,  but I still need to finalize the details.

**Comment by TomCools** [comment]
Shardul Lavekar from Unlogged could be available the 29th. I'll DM you the contact details.

**Comment by lmagnette** [comment]
It's gonna be too complex for Shardul Lavekar to come. I've pinged the Gatling guy to see if one of their speakers would be available.

**Comment by maarten-vandeperre** [comment]
It is the 29th of May?

In case you're still searching for sessions, I could do a talk around clean architecture and its aspects on code and platform level:

- Advantages within code: https://developers.redhat.com/articles/2023/08/08/implementing-clean-architecture-solutions-practical-example
- How to implement this on platform level to achieve a standardized baseline, which doesn't block innovation: https://developers.redhat.com/articles/2024/03/14/standardization-and-innovation-enemies-or-partners-crime

**Comment by lmagnette** [comment]
Yes it will be the 29th. @maarten-vandeperre we still need a second speaker. Do you have a title and an abstract for your talk?

**Comment by maarten-vandeperre** [comment]
Hi,

I have:
**Title**
Future-Proofing Your Software: A Deep Dive into Clean Architecture for Sustainable Software Development

**Abstract**
Are you overwhelmed by the sheer amount of libraries, frameworks and technologies that need to be curated and maintained on a constant basis (and if you are, please don't look into AI yet)? This session explores how Clean Architecture, a paradigm rooted in SOLID and Domain Driven Design, can offer you a solution to keep up with them: we'll have a look what clean architecture is all about, which issues it solves and highlight some pitfalls during a live demo (e.g., why using File APIs, List types, ... within your core layers is not a good idea).

Beyond coding practices, this session will briefly touch upon the applications of Clean Architecture in broader design contexts, such as platform designs using OpenID, serverless implementations, and more (even AI/ML....). By attending this session, you'll leave with a solid understanding of how Clean Architecture principles can help you navigate the complexities of modern software development.

**Comment by lmagnette** [comment]
Looks good to me :-) . @TomCools could you make the nice visual and if you want I can take care of the rest.

**Comment by TomCools** [comment]
![May event](https://github.com/BeJUG/bejug.github.io/assets/11362563/87b2578a-a9b8-4970-91ef-8e687a1fcdca)
