### ISSUE TITLE
[Meetup] June 2024

### ISSUE THREAD

**Issue by FDelporte** [BeJUG/bejug.github.io#42]
Meetup page: https://www.meetup.com/belgian-java-user-group/events/301217259

### Preparation

- [x] Find speaker(s): **@N1cky94, @FDelporte with MC @TomCools**
- [x] Find location: **TVH Waregem**
- [x] Determine date: **Monday June 24**
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

## Context and additional details

![2024 June Event](https://github.com/BeJUG/bejug.github.io/assets/1415873/e425c44e-d269-4878-9a53-2841c5e0742d)

**Comment by FDelporte** [comment]
TVH confirmed we can have the June session in Waregem.
Possible dates: Monday 17, Thursday 20 (preferred by TVH), or Monday 24/6.
Will now start looking for speakers...

**Comment by FDelporte** [comment]
Confirmed speakers for 24/06 at TVH: Simon Ritter (@speakjava) and Steve Poole (@spoole167)

**Comment by N1cky94** [comment]
I understood we are looking for a new Speaker?

I can introduce Stijn Van Raes. He has a general talk on web3 and its possibilities. He will tailor the talk towards the IT industry. But it will be a general talk about web3.

I can also do a quicky, if you guys want, of 15 to 20 minutes.
**Pair programming made easy: GitHub CoPilot** - On how CoPilot can be used as a pair programmer and let you excell as a developer.

**Comment by FDelporte** [comment]
Steve Pool would originally be our second speaker, but he had to cancel because of a double booking...

@N1cky94 yes, please, block your (15' talk) and Stijns (45' talk) agenda for 24/06 ;-)
That would be a great combination! Practical arrangements later...

**Comment by FDelporte** [comment]
Restarting to look for main speaker with Java topic as Simon Ritters agenda also changed and is no longer available in June...

**Comment by N1cky94** [comment]
Stijn can do the talk with content:
```
Afgelopen periode lag de blockchain- en cryptowereld even onder een dikke laag ijs tijdens de 'cryptowinter’. Maar na elke winter komt de lente – en met de lente een hernieuwde interesse in blockchain en web3.  Maar wat is web3 nu precies en wat heeft het jou of je klanten te bieden?  In deze niet-technische intro sessie in web3 vertellen we meer over:  - De essentie van web3 en waarom web2 niet goed genoeg is - De impact die het zal hebben op zowat alle sectoren - De rol van blockchain als de motor achter web3 - de werking van zo’n blockchain (high-level) - De huidige stand van zaken en de uitdagingen die er nog liggen - Plus, een heleboel inspirerende voorbeelden waar het nu al effectief gebruikt wordt
Ik zie dat je spreekt over solid pods, dat is strikt gezien geen web3 maar het verschil ertussen zal ik mee in de sessie opnemen
Zet er ook maar bij:  - verschillen tussen web3 en web3.0
```

I can do a small talk of 15 to 20 minutes on GitHub Copilot.
Or I can do an hour talk on building a Vaadin app.

**Comment by N1cky94** [comment]
Loic Magnette might have a new talk and needs a dry run - Full Stack development Quarkus

**Comment by TomCools** [comment]
@FDelporte has the 20th been confirmed? 😊 it is not clear to me in this conversation. 

Asking because I might already be in Brugge the 20th, so that would be a nice date for me 🤣

**Comment by FDelporte** [comment]
Sorry @TomCools, you'll need to arrange a plane to West-Flanders twice... Date is Monday June 24, I added it now in the initial ticket message.

**Comment by TomCools** [comment]
@FDelporte the speaker name is "****" 😅 is this something we need to resolve still or you keeping it secret. 🤐

**Comment by FDelporte** [comment]
The secret is out, local top speakers ;-)
Working on meetup and canva, will be available for the JUG this week
