### ISSUE TITLE
[Meetup] - December 2024

### ISSUE THREAD

**Issue by N1cky94** [BeJUG/bejug.github.io#45]
### Preparation

- [x] Find speaker(s) > Simon Ritter @speakjava and Badr Kacimi @badrkacimi 
- [x] Define topics 
- [x] Find location > Colruyt Group, Zwijnaarde: Tramstraat 67c, 9052 Gent
- [x] Determine date > Monday 2 December 2024
- [x] Announce event on Meetup.com
- [x] Add event to BeJUG website
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by N1cky94** [comment]
I will querry Sander Mak for a session on the newest in Java 23 that will release in Sept.
And can we maybe find someone who gives a talk on Event Driven with Spring?

**Comment by N1cky94** [comment]
@FDelporte Want to organize this one with me?

**Comment by N1cky94** [comment]
We could do this on a tuesday or wednesday:
- 14, 19, 21, 26 or 28 November

**Comment by FDelporte** [comment]
> @FDelporte Want to organize this one with me?

Sure want to help! Maybe don't schedule speakers too early as most of them have "fluent agendas" which can still shift a lot in the next months...

**Comment by TomCools** [comment]
I'll check with Sander as well.

**Comment by N1cky94** [comment]
Maybe: [Evelien Schellekens](https://www.linkedin.com/in/evelien-schellekens/overlay/about-this-profile/)

**Comment by N1cky94** [comment]
@FDelporte & @TomCools 
Location has been confirmed.

We have set the date for 5th of December 2024 in Colruyt Zwijnaarde.
For now we can still play around with the date. But they wanted us to reserve the room as early as possible.

**Comment by FDelporte** [comment]
@badrkacimi, you proposed a shorty for an earlier BeJUG event. Are you interested in speaking at this one?

**Comment by N1cky94** [comment]
@FDelporte & @TomCools 
I have received all your emails, but apparently, I can't answer because my mailbox is recognized as SPAM.
Looking into this.

I have shared all info internally with Colruyt Group.
I have received a couple questions from CG:
1. Logo should have been from Colruyt Group not Colruyt Laagste prijzen (can we change this?)
2. CG asks If they can interview one of the speakers, before the event. What is the opinion on this?

![CG grijs zijkant links bol 1](https://github.com/user-attachments/assets/147c69e0-3171-48a4-b380-aa843c0b4f3e)
![CG wit zijkant links bol](https://github.com/user-attachments/assets/6a69369f-b573-4ac4-acbe-b6fbf596aa61)

**Comment by FDelporte** [comment]
New pancarte:

![2024 December Event](https://github.com/user-attachments/assets/7387a45f-11e1-44f8-be8b-f4449b1d4f9e)

**Comment by FDelporte** [comment]
I guess @speakjava would be happy to talk about Java for an interview ;-)

**Comment by N1cky94** [comment]
Thanks for the lightning fast response Frank. :D

Simon, would you be open to this?

**Comment by N1cky94** [comment]
@FDelporte , How can I reach out to Simon?

**Comment by TomCools** [comment]
I unfortunately will not be able to attend this one. :(

Just be aware that in the past we have asked companies to not publish a
video interview.
In that case, the video didn't mention BeJUG at all, but was using video
fragments from during the meetup (including close-ups of our attendees).
We don't have official guidelines about this, but I think we agree that we
should keep the JUG a safe space for our attendees and our speakers.

If Simon wants to give an interview, that is entirely up to him. :-) My
concern is about consent.
I would personally not consent to being shown in a video which a company
posts (making it de-facto commercial) without my approval.

I'll add it to the list of items to discuss for next community call:
https://github.com/BeJUG/bejug.github.io/issues/63
I think formalizing our stance on this in the Partnership Guidelines is
probably a good idea.

**Comment by N1cky94** [comment]
Hey FrankIk denk dat ze dit voor het evenement (vandaag, morgen of overmorgen) willen doen via telefoon of teams meeting.Onze afdeling schrijft daar dan een artikel over voor de sociale media. Voornamelijk in het kader van het evenement zelf en de topic die gebracht is. Dus zeker de bedoeling om de JUG centraal te zetten.Zou ik contact gegevens van Simon kunnen krijgen hiervoor? E-mail en/of telefoon zou voldoende moeten zijn.GroetenNick ***@***.*** (0)48 361 86 55On 26 Nov 2024, at 9:33 AM, Tom Cools ***@***.***> wrote:﻿
I unfortunately will not be able to attend this one. :(



Just be aware that in the past we have asked companies to not publish a

video interview.

In that case, the video didn't mention BeJUG at all, but was using video

fragments from during the meetup (including close-ups of our attendees).

We don't have official guidelines about this, but I think we agree that we

should keep the JUG a safe space for our attendees and our speakers.



If Simon wants to give an interview, that is entirely up to him. :-) My

concern is about consent.

I would personally not consent to being shown in a video which a company

posts (making it de-facto commercial) without my approval.



I'll add it to the list of items to discuss for next community call:

https://github.com/BeJUG/bejug.github.io/issues/63

I think formalizing our stance on this in the Partnership Guidelines is

probably a good idea.





On Tue, Nov 26, 2024 at 9:06 AM Nick Bauters ***@***.***>

wrote:
