### ISSUE TITLE
[Meetup] - October 2024

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#49]
### Preparation

- [x] Find speaker(s) 
- [x] Find location (Brussels)
- [x] Determine date (24th)
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

## Context and additional details

Devoxx Belgium is 7 – 11 Oct, so not during that week.

**Comment by DenMette** [comment]
I will see what's available in October, preferably in the 3rd week.

**Comment by TomCools** [comment]
@denmette you got an update on this? 😊

**Comment by TomCools** [comment]
Doing a quick check with potential speakers

**Comment by TomCools** [comment]
@timtebeek has agreed. If it's all good for you @denmette, we can fix the date 😊

**Comment by denmette** [comment]
It's confirmed.
Address:

Romeinsesteenweg 564/Box 4
1853 Grimbergen


You can park in the garage, or on the street (free of charge)

**Comment by TomCools** [comment]
@denmette few more questions:

- how many people?
- food and drinks included?

**Comment by denmette** [comment]
- how many people? 40
- food and drinks included? Yes

**Comment by TomCools** [comment]
@badrkacimi, thank you for your offer. 2 other people beat you to it (via DMs). I would love to have you come speak at some point! Lets stay in touch!

**Comment by TomCools** [comment]
Social Links:

- LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7250797672897417217
- Twitter: https://x.com/BeJUG/status/1843938195979063386
