### ISSUE TITLE
[Meetup] Januari 2023

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#5]
### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by kdubois** [comment]
I'd be happy to do a talk about Quarkus developer experience :)
