### ISSUE TITLE
[Meetup] - November 2024

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#50]
### Preparation

- [x] Find speaker(s) (Secret 4 now ;))
- [ ] Find location
- [x] Determine date (5th)
- [ ] Announce event on Meetup.com
- [ ] Promote on social media

### After the event

- [ ] Send mail to attendees to wrap up
- [ ] Shoutouts on social media
- [ ] Share content (slides / video / images) if/when available
- [ ] Promote next event (If available)

**Comment by DenMette** [comment]
I can ask Sopra Steria to host this event in their offices of Strombeek-Beveren?

**Comment by DenMette** [comment]
@TomCools confirmed for the location.
Food and Drinks will be provided.

**Comment by TomCools** [comment]
Hey @DenMette, i think you moved a bit too fast on this one. We'll probably be doing this in neutral terrain together with BruJUG. 😬

I am in contact with Olivier about this. 
More to be discussed on community call later this week. Sorry for the confusion.

**Comment by DenMette** [comment]
@TomCools , Should I reschedule it in October then?

**Comment by TomCools** [comment]
Sorry for missing this @DenMette ! October would ne better
