### ISSUE TITLE
[Event] May 2023 Voxxed Days Brussels: how can we participate

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#6]
A task to discuss how we can participate in Voxxed Days Brussels: 23 May 2023

Thoughts:

- Promo?
- Speaker Training?
- Booth?
- Surrounding Java activity?

**Comment by TomCools** [comment]
Received mail from the organization:

- They offer a discount code we can send to our members in exchange for some promo.
- The also give us the opportunity to fill a slot with some Quicky Sessions

Both to be discussed in the next community hangout.

**Comment by TomCools** [comment]
Ideas: 

- Toastmasters?
- 5 minute session?  Feedback!
- Help with abstract?

Guidelines on who gets the slots
- Voxxed: 3*15 minutes
- Training: Community (those present) can vote on the most popular talk (top 3 gets selected) 
- Training: 1 week before event, we let you know how long the training presentation should be. (but mention it is going to be a short preview, not a 50 minute session!)
- Voxxed: Fallback in case not enough sign up: fill up rest of slots with experienced speakers?


TODO:

- [ ] Figure out how the voting could work?
- [ ] Check with Olivier what the options are for beginning of may? @TomCools 
- [ ] Ask Toastmasters if they want to participate in this training. @TomCools

**Comment by ohubaut** [comment]
@TomCools, I got a reply from the school. 
They are closed the first week of May.
Should I ask for a reservation on the second week, or should we try to advance this in April?

**Comment by TomCools** [comment]
@ohubaut: Maybe move it up a week to April? We need enough time for people to practice their talks.

**Comment by ohubaut** [comment]
@TomCools Done. Venue reserved for April 27th.

**Comment by TomCools** [comment]
❤️
