### ISSUE TITLE
IT Classics giveaway

### ISSUE THREAD

**Issue by ortwin45** [BeJUG/bejug.github.io#64]
I recently moved and decided I will give away some IT classic books (because I don't read them and I'd like to have a more minimalist life). Maybe some participant in the bejug might be interested? Or not? 

- Domain Driven Design (Evans)
- Design Patterns (Gamma, Helm, Johnson, Vlissides)
- Refactoring (Fowler)
- Enterprise Integration Patterns (Hohpe, Woolf)
- Modern Operating Systems (Tanenbaum)
- Java Concurrency In Practice (Goetz)

**Comment by TomCools** [comment]
As discussed during the community call @TomCools will arrange this with @ortwin45, Handouts at future JUG events.
