### ISSUE TITLE
[Meetup] April 2023

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#7]
### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by TomCools** [comment]
Ronald is willing to host this :)

**Comment by rdehuyss** [comment]
Comment

**Comment by TomCools** [comment]
@rdehuyss , do you have any update on this? Anything we can help with? :)

**Comment by rdehuyss** [comment]
Hi @TomCools ,

- Normally the venue is arranged but I'm double checking as they told me that they would get back to me but this did not happen yet.
- I've asked a great developer (@bdeneuter) that I know who would be willing to talk about how they are using virtual threads already for quite some while in production.

I've reached out to the venue again and will try to arrange the date asap. I'll keep you posted!

**Comment by rdehuyss** [comment]
Small update:
- [x] Find speaker: Bart Deneuter (@bdeneuter) - topic: Virtual Threads in practice
- [x] Find location: Cegeka Leuven / Haasrode, Interleuvenlaan 16 B, 3001 Leuven (vlakbij autostrade)
- [x] Determine date: Dinsdag 18 april

And good news! Cegeka is willing to sponsor food and drinks.

**Comment by bdeneuter** [comment]
@rdehuyss I think there is a misunderstanding. Our backend systems are indeed running on:

- JDK 19 + --preview features (which makes virtual threads available)
- Spring Boot 3/Spring 6 (which makes AOT processing and native compilation available)
- When JDK 20 is released, we will upgrade

But... we were evaluating virtual threads and structured concurrency but had to patch too many libraries to avoid pinned threads. So currently we don't use virtual threads yet in production and decided to wait for the synchronized support (I hope they add it by JDK 21).
We are starting to evaluate Spring AOT processing but it depends on our priorities when we will really invest in it.

So if you are still interested, I can talk on how/why we try to stay on the latest JDK with preview features. Our experience with running preview features in production. So basicly I can give you a dissection of one of our Java micro services and the tooling we have around it.

Feel free to cancel this presentation and find an alternative topic as `Virtual Threads in practice` is of course a catchier topic then another micro service presentation.

**Comment by rdehuyss** [comment]
So - my mistake - we talked a lot about virtual threads that's why I made a mistake on the title of the presentation. Title will be: **Riding the OpenJDK waves: getting barreled?**

Some feedback from @bdeneuter regarding the title in dutch (as I had to look up __getting barreled__) 😆 : 
> Getting barreled is een surf term 😊 Het betekent op uw plank blijven staan terwijl de golf een tunnel maakt. En als je de 6-maandelijkse OpenJDK releases als golven beschouwt, gaat de topic over hoe we deze golf voorbereiden, ingaan en zorgen dat productie overeind blijft

**Comment by TomCools** [comment]
@rdehuyss :I already made a draft event on Meetup.com. You are host so you should be able to edit it.
If you want Lightning talks beforehand, create an issue ticket on Github and I'll arrange the promo for that. 

@bdeneuter: If you got a nice picture for the promo card; could you please send it belgian.jug@gmail.com?

@FDelporte Once I got the promo card ready, i'll let you know so you can add the details to the SlideDeck for the event in March. "Up next! Leuven! :-)"

**Comment by rdehuyss** [comment]
Ok, so change of plans like @TomCools already knows:
- @bdeneuter would prefer not to present due to personal reasons
- I was lucky enough that @snicoll could come as the main speaker with the topic: **The next generation of Spring applications is here!**
- Regarding shorties:
   - a speaker from Cegeka will present "What's new in Java 19 and Java 20"
   - Waiting for confirmation of @ge0ffrey whether he can do a shortie about "A corner case cheat sheet
for Java and JVM languages"
   - I (@rdehuyss)  can do a shortie about "Your sofware architecture may aid global warming"

The Meetup page has been updated but still needs to have a new banner. The link to his profile image can be found here: https://snicoll.be/images/profile.png

**Comment by snicoll** [comment]
👋
